# To fetch schema from
introspection: http://localhost:4000/graphql

servers: # same format as for OpenAPI Specification
  - url: http://localhost:4000/graphql
    description: Dev
  - url: http://localhost:4000/graphql
    description: Prod

info: # same format as for OpenAPI Specification
  title: Homelike APIs
  description: Endpoints for interacting with homelike data.